version: '3.1'
services:
  myapp-mysql:
    image: 'mysql:8.0'
    #container_name: myapp-mysql
    working_dir: /var/www/myapp
    ports:
      - "8106:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=myapp
      - MYSQL_USER=myapp
      - MYSQL_PASSWORD=myapp

  myapp-nginx:
    image: 'neotericlabs/cakeapp-nginx'
    #container_name: myapp-nginx
    working_dir: /var/www/myapp
    #    - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
     - "8180:80"
    depends_on:
            #links:
      - myapp-php-fpm

  myapp-php-fpm:
    image: neotericlabs/php-fpm8.0
    #container_name: myapp-php-fpm
    working_dir: /var/www/myapp
    depends_on:
            #links:
     - myapp-mysql

  myapp-nginx-reverse-proxy:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx-lb/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - myapp-nginx
      - myapp-mysql

  myapp-nginx-health-check:
    image: nginx:latest
    ports:
      - "9090:80"
    healthcheck:
      test: curl --fail http://34.228.38.164 || exit 1
      interval: 1m20s
      timeout: 60s
      #start_period: 20s
      retries: 5
    depends_on:
      - myapp-nginx-reverse-proxy

